apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-task
spec:
  replicas: 2
  selector:
    matchLabels:
      app: add-task
  template:
    metadata:
      labels:
        app: add-task
    spec:
      containers:
      - name: add-task
        env:
        - name: CONNECTION_STRING
          value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:todoserverdev.database.windows.net,1433;Database=tododbdev;Uid=sqladminuser;Pwd=P@ssword1234;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
        image: todoazureacr1.azurecr.io/addtasks:v1
        ports:
        - containerPort: 8000
